import type { MasterData } from "./types";

export const masterData: MasterData = {
  personalInfo: {
    show_portfolio: true,
    show_resume: true,
    fullName: "Md Shoriful Islam Ashiq",
    nickname: "Ashiq",
    email: "ashiq@midgen.ai",
    location: "Dhaka, Bangladesh",
    linkedin: "linkedin.com/in/mdsiaofficial",
    github: "github.com/mdsiaofficial",
    website: "ashiq.pro.bd",
    titles: [
      "Software Engineer",
      "Full-Stack Developer",
      "Strategic Planner",
      "Problem Solver",
    ],
  },
  summary_portfolio:
    "Software Engineer passionate about building production-ready applications, scaling systems, and driving business growth through technology and clean engineering practices.",
  summary_resume:
    "Software Engineer with experience building scalable web applications using React, Next.js, and Node.js. Passionate about clean code, system design, and continuous learning. Adept at collaborating with cross-functional teams to deliver enterprise solutions.",
  experience: [
    {
      show_portfolio: true,
      show_resume: true,
      company: "Code Studio",
      title: "Software Engineer",
      location: "Dhaka, Bangladesh",
      startDate: "November 2024",
      current: true,
      website: "https://code-studio4.com",
      bullets: [
        "Contributing to DevOps implementation and deployments.",
        "Building production-ready applications using React, Next.js, and MySQL.",
        "Collaborating with cross-functional teams to deliver enterprise solutions.",
      ],
      technologies: ["React", "Next.js", "MySQL", "DevOps"],
      image: "https://i.ibb.co/SBJBTT3/atomic.png",
      impact: "Contributed to the DevOps implementation deployments along with the development of production-ready applications",
    },
    {
      show_portfolio: false,
      show_resume: false,
      company: "Code Studio",
      title: "Junior Software Engineer",
      location: "Dhaka, Bangladesh",
      startDate: "November 2024",
      endDate: "December 2025",
      current: false,
      website: "https://code-studio4.com",
      bullets: [
        "Building production-ready applications using React, Next.js, and MySQL.",
        "Collaborating with cross-functional teams to deliver enterprise solutions.",
      ],
      technologies: ["React", "Next.js", "MySQL"],
      image: "https://i.ibb.co/SBJBTT3/atomic.png",
      impact: "Contributed to the development of production-ready applications using React, Next.js, and MySQL.",
    },
    {
      show_portfolio: true,
      show_resume: true,
      company: "Itransition Group",
      title: "Internship Trainee",
      location: "Remote",
      startDate: "September 2024",
      endDate: "October 2024",
      current: false,
      website: "https://www.itransition.com",
      bullets: [
        "Learning JavaScript/Node-based frontend development.",
        "Backend development and basic structure for maintaining production-ready applications.",
      ],
      technologies: ["JavaScript", "Node.js", "React"],
      image: "https://i.ibb.co/SBJBTT3/atomic.png",
      impact: "Contributed to the development of production-ready applications using React, Node.js.",
    },
  ],
  education: [
    {
      show_portfolio: true,
      show_resume: true,
      institution: "City University Bangladesh",
      degree: "B.Sc.",
      field: "Computer Science & Engineering",
      startYear: 2022,
      endYear: 2026,
      gpa: "3.49",
    },
    {
      show_portfolio: true,
      show_resume: true,
      institution: "Govt Bangla College",
      degree: "B.Sc.",
      field: "Mathematics",
      startYear: 2018,
      endYear: 2022,
      gpa: "3.10",
    },
  ],
  skills: [
    {
      show_portfolio: true,
      show_resume: true,
      name: "TypeScript",
      category: "languages",
      description: "My go-to for anything beyond simple scripts. I use it for full-stack type safety — from Next.js frontends to Node.js APIs. Types catch bugs before they reach production.",
      projects: ["CPCCU Portal", "Code Studio apps", "This portfolio"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "JavaScript (ES6+)",
      category: "languages",
      description: "The foundation of everything I build. Deep understanding of closures, event loop, async/await, destructuring, modules, and prototypal inheritance.",
      projects: ["Every web project I've shipped"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "C++",
      category: "languages",
      description: "Used primarily for competitive programming. Comfortable with STL, templates, recursion, dynamic programming, and graph algorithms. Solved 500+ problems across LeetCode and Codeforces.",
      projects: ["ICPC 2022–2025", "Meta Hacker Cup 2023–2024"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "HTML5",
      category: "languages",
      description: "Accessible, SEO-friendly markup. I use semantic elements, ARIA labels, and structured data where it matters.",
      projects: ["All frontend projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "CSS3 / SASS",
      category: "languages",
      description: "Modern layout techniques — Flexbox, Grid, custom properties, animations. I write modular, maintainable stylesheets before reaching for utility frameworks.",
      projects: ["All frontend projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "React",
      category: "frontend",
      description: "Built production apps with hooks, context, custom hooks, lazy loading, and component composition patterns. Comfortable with class components but prefer functional patterns.",
      projects: ["CPCCU Portal", "Book Store MERN", "CRUD Data Table", "AI Content Humanizer"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Next.js",
      category: "frontend",
      description: "My primary framework for React apps. I use App Router, Server Components, API routes, ISR, SSR, and middleware. Handles routing, data fetching, and deployment in one stack.",
      projects: ["Code Studio enterprise apps", "This portfolio"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Tailwind CSS",
      category: "frontend",
      description: "Utility-first styling for rapid UI development. I write custom theme extensions, responsive variants, and component-level utilities. Faster than writing custom CSS from scratch.",
      projects: ["All recent projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Framer Motion",
      category: "frontend",
      description: "Declarative animations for React — page transitions, scroll-triggered effects, layout animations, and gesture-based interactions.",
      projects: ["This portfolio", "CPCCU Portal"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "React Router",
      category: "frontend",
      description: "Client-side routing with nested routes, dynamic segments, loaders, and navigation guards.",
      projects: ["React Router Demo", "Library Management System"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Node.js",
      category: "backend",
      description: "Server-side JavaScript for REST APIs, real-time features, background jobs, and file processing. I use the event-driven model for non-blocking I/O.",
      projects: ["CPCCU Portal backend", "Book Store MERN API", "Code Studio apps"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Express.js",
      category: "backend",
      description: "Lightweight routing and middleware framework. I structure APIs with route modules, error handling middleware, authentication guards, and input validation.",
      projects: ["Book Store"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Hono.js",
      category: "backend",
      description: "Ultra-fast, lightweight web framework of Bun runtime (a native js/ts runtime) for edge runtimes and Node.js. I use it for building type-safe APIs with a Express-like feel but significantly better performance and TypeScript support.",
      projects: ["API prototyping", "Edge functions"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "REST API Design",
      category: "backend",
      description: "Designing clean, consistent RESTful APIs — proper HTTP methods, status codes, pagination, filtering, versioning, and error response formats.",
      projects: ["All backend projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "EJS Templates",
      category: "backend",
      description: "Server-side HTML templating with Embedded JavaScript. I use it for dynamic page rendering, email templates, and generating markup with logic directly in the view layer.",
      projects: ["Server-rendered pages", "Email templating"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Authentication & Authorization",
      category: "backend",
      description: "JWT-based auth, session management, OAuth flows, role-based access control, and password hashing with bcrypt.",
      projects: ["Book Store MERN", "CRUD App MERN"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "MongoDB",
      category: "databases",
      description: "NoSQL document database for flexible schemas. I use Mongoose ODM, aggregation pipelines, indexing for performance, and embedded vs. referenced document patterns.",
      projects: ["CPCCU Portal", "Book Store MERN", "CRUD App MERN"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "PostgreSQL",
      category: "databases",
      description: "Relational database for structured data and complex queries. I use it when data integrity and ACID compliance matter — transactions, joins, and foreign keys.",
      projects: ["Code Studio enterprise apps"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "MySQL",
      category: "databases",
      description: "Used at Code Studio for existing enterprise schemas. Comfortable with queries, indexing, normalization, and stored procedures.",
      projects: ["Code Studio apps"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Git",
      category: "devops",
      description: "Version control for everything. I use feature branches, interactive rebase, cherry-pick, bisect for debugging, and conventional commit messages.",
      projects: ["Every project"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "GitHub Actions",
      category: "devops",
      description: "CI/CD pipelines for automated testing, linting, building, and deployment. I set up workflows for PR checks and production deploys.",
      projects: ["CPCCU Portal CI/CD", "Portfolio auto-deploy"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Docker",
      category: "devops",
      description: "Containerizing apps for consistent environments. I write Dockerfiles, docker-compose for multi-service setups, and use it to onboard new devs quickly.",
      projects: ["Code Studio dev environments"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Vercel",
      category: "devops",
      description: "Zero-config deployments for Next.js apps. I use preview deployments for PRs, environment variables, edge functions, and domain configuration.",
      projects: ["This portfolio", "All Vercel-hosted projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Linux / CLI",
      category: "devops",
      description: "Comfortable working in terminal — bash scripting, SSH, process management, file operations, and server administration.",
      projects: ["All server-side work"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "VS Code",
      category: "tools",
      description: "Primary IDE with a curated extension setup — ESLint, Prettier, GitLens, Tailwind IntelliSense, and Copilot. Custom keybindings for productivity.",
      projects: ["Daily driver for all development"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Cursor",
      category: "tools",
      description: "AI-powered code editor. I use it for rapid prototyping, codebase-aware suggestions, and refactoring with natural language prompts.",
      projects: ["Side projects and experimentation"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Claude Code",
      category: "tools",
      description: "AI assistant for development — debugging complex issues, generating boilerplate, writing tests, and exploring unfamiliar codebases.",
      projects: ["Used across multiple projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "OpenCode",
      category: "tools",
      description: "AI coding agent for agentic development workflows. I use it for multi-step tasks, codebase exploration, and autonomous feature implementation with tool orchestration.",
      projects: ["This portfolio", "Rapid prototyping"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Codex",
      category: "tools",
      description: "OpenAI's coding agent for autonomous software engineering tasks. I use it for code generation, refactoring, and tackling complex engineering problems with contextual understanding.",
      projects: ["Feature development", "Codebase maintenance"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Postman",
      category: "tools",
      description: "API testing and documentation. I use collections, environments, and automated test scripts for backend development.",
      projects: ["All API development"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Figma",
      category: "tools",
      description: "Reading design files and translating them to code. I use it to inspect spacing, colors, typography, and component structure.",
      projects: ["All client-facing projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Responsive Design",
      category: "design",
      description: "Mobile-first approach with breakpoints, fluid typography, and adaptive layouts. Every project I build works across all screen sizes.",
      projects: ["All web projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "UI/UX Principles",
      category: "design",
      description: "Understanding of visual hierarchy, contrast, spacing, affordances, and user flow. I build interfaces that are intuitive before they're beautiful.",
      projects: ["All projects"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Component Design Systems",
      category: "design",
      description: "Building reusable, composable component libraries. I focus on consistent props, variants, and accessibility from the start.",
      projects: ["CPCCU Portal", "Code Studio apps"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Data Structures & Algorithms",
      category: "competitiveProgramming",
      description: "Arrays, linked lists, trees, graphs, hash maps, heaps, stacks, queues. Algorithm paradigms — divide and conquer, greedy, dynamic programming, backtracking.",
      projects: ["ICPC 2022–2025", "Meta Hacker Cup 2023–2024", "LeetCode 500+ problems"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Problem Solving",
      category: "competitiveProgramming",
      description: "Breaking down complex problems into smaller subproblems. Strong pattern recognition for common problem types — sliding window, two pointers, BFS/DFS, topological sort.",
      projects: ["Competitive programming contests"],
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Contest Strategy",
      category: "competitiveProgramming",
      description: "Time management during contests, quick prototyping, identifying easy/medium/hard problems, and knowing when to move on.",
      projects: ["ICPC regional rounds", "Meta Hacker Cup rounds"],
    },
  ],
  certifications: [
    {
      show_portfolio: true,
      show_resume: true,
      name: "JavaScript Essential 1",
      issuer: "Cisco Networking Academy",
      issueDate: "Jun 2024",
      logo: "https://i.ibb.co/dfqYcvx/cisco.png",
      certificate: "https://i.ibb.co/BPsWXxb/Md-Shoriful-Islam-Java-Script-Essen-certificate.png",
    },
  ],
  projects: [
    {
      show_portfolio: false,
      show_resume: false,
      name: "Book Store MERN",
      role: "Full Stack Developer",
      bullets: [
        "Full-stack e-commerce application with admin dashboard.",
        "Cart functionality and payment integration with Stripe.",
      ],
      technologies: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
      startDate: "2024",
      link: "",
      github: "https://github.com/mdsiaofficial/bookstore-project-mern",
      image: "https://i.ibb.co/588FMXF/bookstore.png",
      featured: true,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Personal Portfolio",
      role: "Solo Developer",
      bullets: [
        "Modern portfolio website showcasing projects, experience, and skills.",
        "Responsive design with smooth animations.",
      ],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      startDate: "2024",
      link: "https://ashiq.pro.bd",
      github: "https://github.com/mdsiaofficial/ashiq-portfolio/",
      image: "https://i.ibb.co/vJVwPYk/p1.png",
      featured: true,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "AI Content Humanizer",
      role: "Full Stack Developer",
      bullets: [
        "AI-powered tool to transform robotic text into natural, human-like content.",
        "Integration with OpenAI API for content transformation.",
      ],
      technologies: ["React", "Tailwind CSS", "OpenAI API"],
      startDate: "Jun 2024",
      link: "https://humanize-frontend-design-react.vercel.app/",
      github: "https://github.com/mdsiaofficial/Humanize-Frontend-Design-React/",
      image: "https://i.ibb.co/V2TxgVY/p2.png",
      featured: true,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "CRUD App MERN",
      bullets: [
        "Production-ready CRUD application with RESTful API.",
        "Authentication and responsive admin dashboard.",
      ],
      technologies: ["React", "Node.js", "Express", "MongoDB"],
      startDate: "Aug 2024",
      github: "https://github.com/mdsiaofficial/crud-app-mern",
      image: "https://i.ibb.co/sWYTJ0v/crudapp.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Positivus - Digital Marketing",
      bullets: [
        "Landing page for digital marketing agency.",
        "Modern UI and responsive design.",
      ],
      technologies: ["React", "Tailwind CSS"],
      startDate: "Jun 2024",
      link: "https://positivus-frontend-react.vercel.app/",
      github: "https://github.com/mdsiaofficial/Positivus-Frontend-react/",
      image: "https://i.ibb.co/9tKBBD6/p3.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "CRUD Data Table",
      bullets: [
        "Interactive data table with create, read, update, delete operations.",
        "Filtering and sorting functionality.",
      ],
      technologies: ["React", "Tailwind CSS"],
      startDate: "Jun 2024",
      link: "https://crud-data-table-project-reactjs.vercel.app/",
      github: "https://github.com/mdsiaofficial/CRUD-data-table-project-reactjs",
      image: "https://i.ibb.co/jzypTmn/crud.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Kanban Board",
      bullets: [
        "Task management board with drag-and-drop functionality.",
        "Task categorization and status tracking.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Mar 2024",
      link: "https://mdsiaofficial.github.io/Kanban_Board/",
      github: "https://github.com/mdsiaofficial/Kanban_Board",
      image: "https://i.ibb.co/vC9mrj0/kanban.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Weather Dashboard",
      bullets: [
        "Real-time weather application with forecasts.",
        "Beautiful UI and smooth animations.",
      ],
      technologies: ["HTML", "CSS", "JavaScript", "Weather API"],
      startDate: "Feb 2024",
      link: "https://mdsiaofficial.github.io/Weather-app/",
      github: "https://github.com/mdsiaofficial/Weather-app",
      image: "https://i.ibb.co/Cz9fd34/weather.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "AI Company Website",
      bullets: [
        "Modern landing page for AI company with service sections and animations.",
      ],
      technologies: ["React", "Tailwind CSS"],
      startDate: "Jun 2024",
      link: "https://gpt-project-eosin.vercel.app/",
      github: "https://github.com/mdsiaofficial/gpt-project/",
      image: "https://i.ibb.co/zNHSfp5/gpt.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Quiz Application",
      bullets: [
        "Interactive quiz app with score tracking and multiple categories.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Feb 2024",
      link: "https://mdsiaofficial.github.io/Quiz-App/",
      github: "https://github.com/mdsiaofficial/Quiz-App",
      image: "https://i.ibb.co/4K79tqj/quiz.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Restaurant App UI",
      bullets: [
        "Food delivery app interface with menu browsing and cart functionality.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Apr 2024",
      link: "https://mdsiaofficial.github.io/Food-App/",
      github: "https://github.com/mdsiaofficial/Food-App",
      image: "https://i.ibb.co/4R0K6gt/restaurant.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Todo Application",
      bullets: [
        "Task management app with add, complete, and delete functionality.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Feb 2024",
      link: "https://mdsiaofficial.github.io/Todo-app-for-org/",
      github: "https://github.com/mdsiaofficial/Todo-app-for-org/",
      image: "https://i.ibb.co/850SYzP/todo.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Analog Clock",
      bullets: [
        "Real-time analog clock with smooth animations and customizable themes.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Apr 2024",
      link: "https://mdsiaofficial.github.io/Analog_Clock/",
      github: "https://github.com/mdsiaofficial/Analog_Clock",
      image: "https://i.ibb.co/KGCptjx/analog.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Club Portal",
      bullets: [
        "Clean university club website with event listings and member information.",
      ],
      technologies: ["HTML", "CSS", "JavaScript"],
      startDate: "Apr 2024",
      link: "https://mdsiaofficial.github.io/Club-Portal/",
      github: "https://github.com/mdsiaofficial/Club-Portal",
      image: "https://i.ibb.co/gTCp6Wx/club.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "React Router Demo",
      bullets: [
        "Practice project demonstrating React Router for multi-page navigation.",
      ],
      technologies: ["React", "React Router", "Tailwind CSS"],
      startDate: "May 2024",
      link: "https://react-router-project-nine-kappa.vercel.app/",
      github: "https://github.com/mdsiaofficial/react-router-project/",
      image: "https://i.ibb.co/ZTHZMqt/reactrouter.png",
      featured: false,
    },
    {
      show_portfolio: false,
      show_resume: false,
      name: "Library Management System",
      bullets: [
        "Practice project demonstrating React Router for multi-page navigation.",
      ],
      technologies: ["React", "React Router", "Tailwind CSS"],
      startDate: "Dec 2025",
      link: "https://library-cse416.netlify.app/",
      github: "https://github.com/mdsiaofficial/library-project/",
      image: "https://i.ibb.co/ZTHZMqt/reactrouter.png",
      featured: false,
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "NTEX Sourcing",
      role: "Full Stack Developer",
      bullets: [
        "Full-stack B2B e-commerce platform for textile sourcing.",
        "Vendor management, order tracking, and payment processing.",
      ],
      technologies: ["Next.js", "Express.js", "MongoDB", "GCP"],
      startDate: "2024",
      endDate: "Present",
      link: "https://ntexsourcing.com/",
      image: "https://i.ibb.co/n353KBb/cpccu.png",
      featured: false,
      deployment: "Google Cloud Platform",
      architecture: "Full Stack",
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Visual Center",
      role: "Full Stack Developer",
      bullets: [
        "Full Functional Udemy-like Learning Management System.",
        "Real-time visual analytics and content management platform.",
        "Live streaming integration and dashboard analytics.",
      ],
      technologies: ["Next.js", "Express.js", "MongoDB", "VPS"],
      startDate: "2024",
      endDate: "Present",
      link: "https://visualcenter.live/",
      image: "https://i.ibb.co/n353KBb/cpccu.png",
      featured: true,
      deployment: "VPS Deployment",
      architecture: "Full Stack",
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "Midgen AI",
      role: "Full Stack",
      bullets: [
        "AI-powered content creation platform with humanizer, article writer, and SEO tools.",
        "Serving thousands of users globally.",
      ],
      technologies: ["Next.js", "Express.js", "MongoDB", "GCP"],
      startDate: "2024",
      endDate: "Present",
      link: "https://midgen.ai/",
      image: "https://i.ibb.co/n353KBb/cpccu.png",
      featured: true,
      deployment: "Google Cloud Platform",
      architecture: "Full Stack",
    },
    {
      show_portfolio: true,
      show_resume: true,
      name: "CPCCU Portal",
      role: "Lead Developer",
      bullets: [
        "Club management platform for Competitive Programming Camp at City University.",
        "Serving 500+ student members with contest management and resource sharing.",
      ],
      technologies: ["React", "Tailwind CSS", "Node.js", "MongoDB"],
      startDate: "2024",
      endDate: "Present",
      link: "https://cpccu.club",
      github: "https://github.com/cpccu/cpccu/",
      image: "https://i.ibb.co/n353KBb/cpccu.png",
      featured: false,
      deployment: "VPS Deployment",
      architecture: "Full Stack",
    },
  ],
  achievements: [
    {
      show_portfolio: true,
      show_resume: true,
      title: "ACM ICPC 2025",
      issuer: "ICPC Foundation",
      date: "Oct 2025",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "ACM ICPC 2024",
      issuer: "ICPC Foundation",
      date: "Oct 2024",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "Meta Hacker Cup 2024",
      issuer: "Meta",
      date: "Oct 2024",
      location: "Meta Coding Competitions",
      description: "Meta's annual open programming competition.",
      logo: "https://i.ibb.co/y5QQwH7/metahackercup.png",
      certificate: "https://i.ibb.co/fD7Jkg9/Meta-Hacker-Cup2023.jpg",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "ACM ICPC 2023",
      issuer: "ICPC Foundation",
      date: "Oct 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "Meta Hacker Cup 2023",
      issuer: "Meta",
      date: "Sept 2023",
      location: "Meta Coding Competitions",
      description: "Meta's annual open programming competition.",
      logo: "https://i.ibb.co/y5QQwH7/metahackercup.png",
      certificate: "https://i.ibb.co/fD7Jkg9/Meta-Hacker-Cup2023.jpg",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "ACM ICPC 2022",
      issuer: "ICPC Foundation",
      date: "Mar 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      show_portfolio: true,
      show_resume: true,
      title: "23rd Intra University Programming Contest - Champion",
      issuer: "City University",
      date: "Oct 2022",
      location: "City University",
      description: "Annual Programming Contest of algorithmic programming for students.",
      logo: "https://i.ibb.co/pQw9xhj/cityuni.png",
      certificate: "https://i.ibb.co/pQYDWPx/cupc2022.png",
    },
  ],
  volunteerExperience: [
    {
      show_portfolio: true,
      show_resume: true,
      organization: "Open Source Software Community City University (OSSCCU)",
      role: "Founding Convenor",
      startDate: "March 2026",
      endDate: "Present",
      current: true,
      description: "Founded and led the open source community at City University. Organized hackathons, workshops on open source contribution, and mentored 300+ students in collaborative development practices.",
      website: "https://www.ossccu.pro.bd",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      show_portfolio: true,
      show_resume: true,
      organization: "City University Programming Club (CUPC)",
      role: "Former President",
      startDate: "September 2024",
      endDate: "November 2025",
      current: false,
      description: "Reformed and led the largest programming club at City University with 500+ members. Organized workshops, contests, and mentoring sessions.",
      website: "https://www.cupc.club",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },

    {
      show_portfolio: true,
      show_resume: true,
      organization: "City University Computer Club (CUCC)",
      role: "Former Vice President",
      startDate: "September 2024",
      endDate: "November 2025",
      current: false,
      description: "Reformed and led the largest programming club at City University with 500+ members. Organized workshops, contests, and mentoring sessions.",
      website: "https://www.cucc.club",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      show_portfolio: true,
      show_resume: true,
      organization: "BASIS Student Forum City University Chapter",
      role: "Former Co-Convenor",
      startDate: "April 2024",
      endDate: "December 2025",
      current: false,
      description: "Leading tech community initiatives and representing BASIS at university level. Built partnerships and organized industry events.",
      website: "https://www.basis.org.bd",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      show_portfolio: true,
      show_resume: true,
      organization: "Competitive Programming Camp City University (CPCCU)",
      role: "Former President",
      startDate: "January 2024",
      endDate: "September 2025",
      current: false,
      description: "Founded the club and organized training programs and contests to prepare students for ICPC. Managed a team of 20+ volunteers and coordinated events for 500+ participants.",
      website: "https://www.cpccu.club",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      show_portfolio: true,
      show_resume: true,
      organization: "Competitive Programming Camp City University (CPCCU)",
      role: "Former Convenor",
      startDate: "October 2022",
      endDate: "January 2024",
      current: false,
      description: "Founded the club and organized training programs and contests to prepare students for ICPC.",
      website: "https://www.cpccu.club",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
  ],
  languages: [
    {
      show_portfolio: true,
      show_resume: true,
      language: "Bengali",
      proficiency: "Native",
    },
    {
      show_portfolio: true,
      show_resume: true,
      language: "English",
      proficiency: "Professional Working",
    },
  ],
  socialLinks: {
    linkedin: "https://linkedin.com/in/mdsiaofficial",
    github: "https://github.com/mdsiaofficial",
    medium: "https://medium.com/@mdsiaofficial",
    email: "ashiq@midgen.ai",
    leetcode: "https://leetcode.com/mdsiaofficial",
    codeforces: "https://codeforces.com/profile/mdsiaofficial",
  },
};

export const portfolioData = masterData;
